# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and distribute to Firebase App Distribution"
  lane :beta do
    increment_build_number(
      xcodeproj: "poc_cicd.xcodeproj"
    )

    build_app(
      workspace: "poc_cicd.xcworkspace",
      scheme: "poc_cicd",
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "poc_cicd.ipa"
    )

    firebase_app_distribution(
      app: "poc-cicd-35e11",
      testers: "hanifhasan91@gmail.com",
      release_notes: "New Beta Version",
      firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
